layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  - owner:
      login: takuseno
    name: d3rlpy
    description: Data-Driven Deep Reinforcement Learning Library as an Out-of-the-box Tool.
    stargazers_count: 2
    forks_count: 0
  - owner:
      login: takuseno
    name: ppo
    description: Proximal Policy Optimization implementation with TensorFlow
    stargazers_count: 78
    forks_count: 21
  - owner:
      login: sony
    name: nnabla
    description: Neural Network Libraries
    stargazers_count: 2.3k
    forks_count: 291
  - owner:
      login: takuseno
    name: d4rl-pybullet 
    description: Datasets for Data-Driven Deep Reinforcement Learning with PyBullet environments
    stargazers_count: 6
    forks_count: 0
  - owner:
      login: takuseno
    name: d4rl-atari
    description: Datasets for Data-Driven Deep Reinforcement Learning with Atari (wrapper for datasets released by Google)
    stargazers_count: 5
    forks_count: 0
  - owner:
      login: sony
    name: nnabla-ext-cuda
    description: A CUDA Extension of Neural Network Libraries
    stargazers_count: 75
    forks_count: 26

topics:
  - name: TensorFlow
    web_url: https://github.com/topics/tensorflow 
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/tensorflow/tensorflow.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Ruby on Rails
    web_url: https://github.com/topics/rails
    image_url: https://raw.githubusercontent.com/github/explore/fd96fceccf8c42c99cbe29cf0f8dcc4736fcb85a/topics/rails/rails.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: React
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/react/react.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/linux/linux.png

  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://raw.githubusercontent.com/github/explore/ccc16358ac4530c6a69b1b80c7223cd2744dea83/topics/php/php.png

  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/github/explore/a3520d60fbf9b0bdd0b7d563a1a3ed596acd8489/topics/android/android.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/docker/docker.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png

  - name: C
    web_url: https://github.com/topics/c
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/c/c.png

  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/cpp/cpp.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/git/git.png

works:
  - name: Sony AI Inc
    position: Machine Learning Engineer
    period: 2020/10 -

  - name: Okinawa Institute of Science and Technology (OIST)
    position: Research Assistant (Neural Computation Unit)
    period: 2020/03 - 2020/07

  - name: Sony Corporation, R&D Center
    position: Part-time Machine Learning Researcher
    period: 2018/11 - 2020/07

  - name: Ghelia Inc
    position: Part-time Machine Learning Researcher
    period: 2018/04 - 2020/07

  - name: Wantedly
    position: Part-time Web Engineer (full stack) & Machine Learning Engineer
    period: 2016/03 - 2018/03

  - name: MatchinGood
    position: Part-time Web Engineer (full stack)
    period: 2014/10 - 2016/03

papers:
  - title: Takuma Seno, Kohei Okuoka, Masahiko Osawa, Michita Imai, "Adaptive Semi-autonomous Agents via Episodic Control", 6th International Conference on Human-Agent Interaction (Poster), 2018
  - title: Takuma Seno, Masahiko Osawa, Michita Imai, "An Intrinsically Motivated Robot Explores Non-reward Environments With Output Arbitration", Annual International Conference on Biologically Inspired Cognitive Architectures, 2018
  - title: Masahiko Osawa, Yuta Ashihara, Takuma Seno, Michita Imai, Satoshi Kurihara, Accumulator Based Arbitration Model for both Supervised Learning and Reinforcement Learning Inspired by Prefrontal Cortex, ICONIP2017.

awards:
  - title: Exploratory IT Human Resources Project (MITOU Program) by Information-technology Promotion Agency (IPA), Japan.
    date: 2020/06 - 2021/03
  - title: Best Presentation Award at the 29th Japanese Neural Network Society in Tokyo.
    date: 2019/9
  - title: Outstanding & AGI Prize at the forth Whole Brain Architecture Hackathon in Tokyo.
    date: 2018/10
  - title: Outstanding Student Prize at 80th Annual Conference of Information Processing Society of Japan in Tokyo.
    date: 2018/03
  - title: Outstanding Student Prize at Human-Agent Interaction Symposium for our research "Relation Between Predictive Cognition and Timing; Non-natural Language Communication Robot and Language Game" in Kanazawa.
    date: 2017/12
  - title: Grand Prize at the third Whole Brain Architecture Hackathon in Tokyo.
    date: 2017/8
